name: Deploy to Server

on:
  push:
    branches:
      - main  # Changed default branch to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}  # Ensure this matches the secret name

      - name: Run deployment script
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@api.naaviverse.com << 'EOF'
            cd /home/ubuntu/naaviverse-8
            ./deploy.sh main  # Pass 'main' branch directly
          EOF